# Generated by Django 4.2.2 on 2023-07-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(blank=True, upload_to="images/team")),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "db_table": "team_member",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subtitle", models.CharField(blank=True, max_length=250, null=True)),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("teammember", models.ManyToManyField(to="team.teammember")),
            ],
            options={
                "db_table": "team",
                "managed": True,
            },
        ),
    ]
