image: docker:20.10.17

services:
  - docker:20.10.17-dind

#variables:
 # DOCKER_TLS_CERTDIR: "/certs"
  #CI_REGISTRY_USER: "walidmbarek"
  #CI_REGISTRY_PASSWORD: "walid123$"
  #CI_REGISTRY: "registry.gitlab.com" !!!!!!!!!!!!!!

stages:
  - test
  - build
  #- deploy

unit_test:
  stage: test
  script:
    - echo "Starting unit test"
    # Add your unit testing commands here
    - echo "Test cases completed"





dev_build_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/test1242319/backdjango .
    - docker push registry.gitlab.com/test1242319/backdjango

