image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  AWS_DEFAULT_REGION: "us-east-1"
  ECR_REGISTRY: "864981720628.dkr.ecr.us-east-1.amazonaws.com/ecr-repo"
  ECR_REPOSITORY: "smartivate-backend"
  CLUSTER_NAME: "my-ekss-cluster"

before_script:
  - apk update && apk add --no-cache curl jq python3 py3-pip
  - python3 -m venv /tmp/venv
  - . /tmp/venv/bin/activate
  - pip install awscli
  - aws --version
  - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 864981720628.dkr.ecr.us-east-1.amazonaws.com/ecr-repo

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA .
    - docker tag $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA $ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA
    - echo "Pushing Docker image to ECR..."
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA
  only:
    - feriel

deploy:
  stage: deploy
  script:
    - echo "Triggering Argo CD sync..."
    - kubectl apply -f k8s-manifests/argo-cd.yaml
  only:
    - feriel
