stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-north-1"
  ECR_REGISTRY: "905418230821.dkr.ecr.eu-north-1.amazonaws.com"
  ECR_REPOSITORY: "my-django-app"

before_script:
  - apk add --no-cache curl jq python3 py3-pip
  - pip3 install awscli
  - aws --version
  - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY)

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA .
    - docker tag $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA $ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA
    - echo "Pushing Docker image to ECR..."
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA
  only:
    - feriel

deploy:
  stage: deploy
  script:
    - echo "Updating Kubernetes deployment..."
    - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
    - kubectl set image deployment/my-django-app my-django-app=$ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA -n default
only:
    - feriel
