stages:
  - build
  - security_scan

before_script:
  - echo "installing AWS CLI"
  - apk add --no-cache curl jq python3 py3-pip
  - apk add --no-cache aws-cli
  - apk add --no-cache openssl
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set default.region us-east-1
  - aws --version
  - docker --version
  - aws configure list

push_to_ecr:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:    
    - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 905418230821.dkr.ecr.eu-north-1.amazonaws.com
    - docker build -t smartovate_repo .
    - docker tag smartovate_repo:latest 905418230821.dkr.ecr.eu-north-1.amazonaws.com/smartovate_repo:latest
    - docker push 905418230821.dkr.ecr.eu-north-1.amazonaws.com/smartovate_repo:latest
    - cd nginx
    - openssl genrsa -out smartovate.key 4096
    - openssl req -new -x509 -days 3650 -key smartovate.key -out smartovate.cert -subj "/C=UK/ST=London/L=London/O=Caustaza Group LTD/CN=smartovate.io"
    - docker build -t nginx:v1 .
    - docker tag nginx:v1 $ECR_REGISTRY_URL/$ECR_REPO_NAME:nginx
    - docker push $ECR_REGISTRY_URL/$ECR_REPO_NAME:nginx
  tags:
    - docker
    - aws

security_scan:
  stage: security_scan
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apt-get update && apt-get install -y curl
    - apt-get install -y awscli
    - apt-get install -y docker.io
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY_URL
  script:
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.1
    - trivy --no-progress --output scanning-report.txt $ECR_REGISTRY_URL/$ECR_REPO_NAME:frontend
  artifacts:
    reports:
      container_scanning: scanning-report.txt
  tags:
    - docker
    - aws
