image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  AWS_DEFAULT_REGION: "us-east-1"
  ECR_REGISTRY: "905418230821.dkr.ecr.us-east-1.amazonaws.com"
  ECR_REPOSITORY: "smartovate_repo"
  CLUSTER_NAME: "smartovate-cluster"

before_script:
  - apk update && apk add --no-cache curl jq python3 py3-pip
  - python3 -m venv /tmp/venv
  - . /tmp/venv/bin/activate
  - pip install awscli
  - aws --version
  - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418230821.dkr.ecr.us-east-1.amazonaws.com

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA .
    - docker tag $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA $ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA
    - echo "Pushing Docker image to ECR..."
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA
  only:
    - feriel

deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes using Argo CD..."
    - kubectl apply -f deployment.yaml
  only:
    - feriel
