stages:
  - build
  - test
  - release


build-job:
  tags:
    - docker
  stage: build
  script:
    - echo "creating virtual environment for the project..."
    - virtualenv $(pwd)/envs
    - source $(pwd)/envs/bin/activate
    - echo "Installing requirements..."
    - pip install -r requirements.txt
    - deactivate


test-job:
  tags:
    - docker
  stage: test
  script:
    - echo "Activating virtual environment..."
    - source $(pwd)/venv/bin/activate
    - echo "Running unit tests..."
    - python manage.py test budget
    - echo "Checking the server..."
    - python manage.py runserver &
    - sleep 10
    - curl -sSf http://localhost:8000 > /dev/null && echo "Server is Up"
    - sudo pkill python
    - deactivate
    - echo "All tests successfully passed."


release-job:
  tags:
    - docker
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t registry.gitlab.com/test1242319/backdjango .
    - docker push registry.gitlab.com/test1242319/backdjango

