stages:
  - lint
  - test

variables:
  POSTGRES_USER: 'caustaza_backend_project'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_caustaza_backend_project'
  POSTGRES_HOST_AUTH_METHOD: trust

pytest:
  stage: test
  image: docker/compose:1.29.2
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker-compose -f local.yml build django
    # Ensure celerybeat does not crash due to non-existent tables
    - make migrate
    - make run-dev
  script:
    - docker-compose -f local.yml run django pytest
    - docker image ls
