stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-north-1"
  ECR_REGISTRY: "905418230821.dkr.ecr.eu-north-1.amazonaws.com"
  ECR_REPOSITORY: "my-django-app"
  CLUSTER_NAME: "smartovate-cluster"

before_script:
  - apk update && apk add --no-cache curl jq python3 py3-pip
  - apk add --no-cache docker
  - service docker start
  - python3 -m venv /tmp/venv
  - . /tmp/venv/bin/activate
  - pip install awscli
  - . /tmp/venv/bin/activate && aws --version
  - . /tmp/venv/bin/activate && $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY)

build:
  stage: build
  script:
    - . /tmp/venv/bin/activate
    - echo "Building Docker image..."
    - docker build -t $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA .
    - docker tag $ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA $ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA
    - echo "Pushing Docker image to ECR..."
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$CI_COMMIT_SHORT_SHA
  only:
    - feriel

deploy:
  stage: deploy
  script:
    - . /tmp/venv/bin/activate
    - echo "Deploying to Kubernetes using Argo CD..."
    - kubectl apply -f deployment.yaml
  only:
    - feriel
