image: docker:20.10.17

services:
  - docker:20.10.17-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

dev_build_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:dev-latest .
    - docker push $CI_REGISTRY_IMAGE:dev-latest

  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
    - changes:
        - Dockerfile

staging_build_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - if [[ "$CI_COMMIT_REF_NAME" == "staging" && "$CI_COMMIT_TITLE" =~ ^stg-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE .;
        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE;
      else
        echo "Invalid staging branch commit message. Build failed.";
        exit 1;
      fi

  rules:
    - if: $CI_COMMIT_REF_NAME == "staging"
    - changes:
        - Dockerfile

production_build_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - if [[ "$CI_COMMIT_REF_NAME" == "main" && "$CI_COMMIT_TITLE" =~ ^prod-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE .;
        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE;
      else
        echo "Invalid production branch commit message. Build failed.";
        exit 1;
      fi

  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
    - changes:
        - Dockerfile
