version : "3.8"
services:
  postgres:
    image: postgres
    container_name: database
    ports:
      - 5432:5432

    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB= mydatabase
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      #- ./data_init/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=your_email@example.com
      - PGADMIN_DEFAULT_PASSWORD=your_password
    ports:
      - 5050:80
    depends_on:
      - postgres

  api:
    image: caustaza
    container_name: backend
    build: 
      context: ./caustaza
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./caustaza/caustaza/.env
    


