# Generated by Django 4.2.7 on 2023-12-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
