# Generated by Django 4.2.2 on 2023-06-21 22:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pageindex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True)),
                ('about_title', models.CharField(blank=True, max_length=255, null=True)),
                ('about_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True)),
                ('service_title', models.CharField(blank=True, max_length=255, null=True)),
                ('service_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('service_description', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_title', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_title', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='This shows at the top of the browser, usually in the tab.', max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Optimal length is roughly 155 characters', max_length=180, null=True)),
            ],
        ),
    ]
