# Generated by Django 4.2.2 on 2023-06-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageindex',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='pageindex',
            name='about_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageindex',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageindex',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
