# Generated by Django 4.2.2 on 2023-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_pageindex_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='images/clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pageindex',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='pageindex',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='pageindex',
            name='description',
        ),
        migrations.AlterField(
            model_name='pageindex',
            name='service_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
