# Generated by Django 4.2.2 on 2023-06-22 15:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_feedbackclient_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackclient',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pageindex',
            name='about_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pageindex',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True),
        ),
    ]
