openapi: 3.0.3
info:
  title: Caustaza API
  version: 1.0.0
  description: API for Caustaza website
paths:
  /AboutUs/:
    get:
      operationId: AboutUs_list
      tags:
      - AboutUs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/About'
          description: ''
components:
  schemas:
    About:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          nullable: true
          maxLength: 250
        subtitle:
          type: string
          nullable: true
          maxLength: 250
        meta_title:
          type: string
          nullable: true
          maxLength: 250
        meta_description:
          type: string
          nullable: true
          maxLength: 250
        description:
          type: string
          nullable: true
          maxLength: 250
        long_description:
          type: string
          nullable: true
          maxLength: 250
      required:
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
