apiVersion: apps/v1  # Spécifie la version de l'API Kubernetes utilisée pour ce déploiement
kind: Deployment  # Indique que nous définissons un objet de type "Deployment"
metadata:
  name: smartovate-backend  # Nom du déploiement, utilisé pour identifier ce déploiement dans Kubernetes
spec:
  replicas: 2  # Définit le nombre de répliques pour ce déploiement, ici nous avons deux instances du backend
  selector:
    matchLabels:
      app: smartovate-backend  # Critère de sélection pour associer les Pods à ce déploiement, basé sur le label "app"
  template:
    metadata:
      labels:
        app: smartovate-backend  # Label appliqué aux Pods créés par ce modèle de déploiement
    spec:
      containers:
      - name: backend  # Nom du conteneur
        image: 905418230821.dkr.ecr.us-east-1.amazonaws.com/smartivate-backend  # Image Docker utilisée pour le conteneur, tirée de l'Amazon ECR

        ports:
        - containerPort: 8000  # Définit le port exposé par le conteneur
