apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartovate-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartovate-backend
  template:
    metadata:
      labels:
        app: smartovate-backend
    spec:
      containers:
      - name: backend
        image: 017820705556.dkr.ecr.eu-north-1.amazonaws.com/my-ecr-repo
 

        ports:
        - containerPort: 8000
